export { default as reveal } from './reveal'
export { default as parallax } from './parallax'
export { default as videoPlay } from './video'
export { default as menu } from './menu'
export { default as cursor } from './cursor'